# XDV Kernel Workspace Manifest
# The XDV Kernel - A Dust Programming Language operating system kernel

[workspace]
name = "xdv"
version = "0.2.0"
description = "XDV Kernel - A Dust Programming Language operating system for x64"

[workspace.sectors]
xdv_dal = "../xdv-dal"
xdv_cds = "../xdv-cds"
xdv_umf = "../xdv-umf"
xdv_hypervisor = "../xdv-hypervisor"
xdv_sdbm = "../xdv-sdbm"

[[sector]]
name = "xdv_boot"
path = "sector/xdv_boot"

[[sector]]
name = "xdv_memory"
path = "sector/xdv_memory"

[[sector]]
name = "xdv_cpu"
path = "sector/xdv_cpu"

[[sector]]
name = "xdv_drivers"
path = "sector/xdv_drivers"

[[sector]]
name = "xdv_kernel"
path = "sector/xdv_kernel"

[[sector]]
name = "xdv_qdomain"
path = "sector/xdv_qdomain"

[[sector]]
name = "xdv_phidomain"
path = "sector/xdv_phidomain"

[[sector]]
name = "xdv_odt"
path = "sector/xdv_odt"

[target.x64-pc-none]
linker = "ld"
linker_flags = ["-nostdlib", "-static"]
